# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Kevin Morris
# Description of the Site
description: DevOps Engineer
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
# below is ny cityscape
# heroimage: https://images.pexels.com/photos/290595/pexels-photo-290595.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2
# below original hero hoodie city rooftop 
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: kevinmorrisone@icloud.com
facebook_username:
twitter_username: kevinmorrisone
instagram_username:
linkedin_username: kevinmorrisone
github_username:  kevinmorrisone
youtube_channel_id:
reddit_username: /DevOpsBro
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname:

# Name of the Author
author-name: Kevin Morris
# URL for the Image of the Author
# author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
author-image: https://media.licdn.com/dms/image/v2/D4E03AQEnWIcjwUznIg/profile-displayphoto-shrink_200_200/B4EZSFxhOjGwAc-/0/1737411138787?e=1752105600&v=beta&t=6pu0nou_a8M9dbsVHjfK-ngFeWk1oEco8onWtFm1Fuc
# 60 Words About the Author
author-about: It's a work in progress. Fun getting to learn and deploy Jekyll.  Looking forward to blogging directly from the CLI in Markdown.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/kevinmorrisone

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
